<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';
$q=trim((string)($_GET['q']??''));$skillId=(int)($_GET['skill_id']??0);$skills=all_skills();
$sql="SELECT res.*,r.participant_name,r.institution,s.name AS skill_name,z.name AS zone_name FROM results res JOIN registrations r ON r.id=res.registration_id JOIN skills s ON s.id=r.skill_id JOIN zones z ON z.id=r.zone_id WHERE res.is_published=1 AND r.status='approved'";$params=[];
if($q!==''){$sql.=' AND (r.participant_name LIKE ? OR r.institution LIKE ? OR s.name LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like);}if($skillId){$sql.=' AND r.skill_id=?';$params[]=$skillId;}$sql.=' ORDER BY s.sort_order,COALESCE(res.rank_position,999),res.score DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$pageTitle='Keputusan';$activePage='keputusan';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';
?>
<section class="dashboard-header"><div class="container text-center"><h1>Keputusan Pertandingan</h1><p>Keputusan rasmi yang telah diterbitkan.</p></div></section>
<section class="container py-4"><form method="get" class="card card-body shadow-sm"><div class="row g-3"><div class="col-lg-7"><input name="q" value="<?= e($q) ?>" class="form-control" placeholder="Cari peserta, kolej atau bidang"></div><div class="col-lg-3"><select name="skill_id" class="form-select"><option value="0">Semua bidang</option><?php foreach($skills as $s): ?><option value="<?= (int)$s['id'] ?>" <?= selected($skillId,$s['id']) ?>><?= e($s['name']) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><button class="btn btn-primary w-100">Cari</button></div></div></form>
<div class="table-responsive mt-4"><table class="table table-bordered table-hover"><thead><tr><th>Kedudukan</th><th>Peserta</th><th>Kolej/Zon</th><th>Bidang</th><th>Markah</th><th>Anugerah</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td class="text-center"><?= $r['rank_position']?e($r['rank_position']):'-' ?></td><td><?= e($r['participant_name']) ?></td><td><?= e($r['institution']) ?><br><small class="text-muted"><?= e($r['zone_name']) ?></small></td><td><?= e($r['skill_name']) ?></td><td class="text-center"><?= number_format((float)$r['score'],2) ?></td><td class="text-center"><span class="badge <?= e(CompetitionService::medalBadge($r['award'])) ?>"><?= e($r['award']) ?></span></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="6" class="text-center text-muted py-4">Belum ada keputusan diterbitkan.</td></tr><?php endif; ?></tbody></table></div>
<div class="card mt-4"><div class="card-body"><h2 class="h5">Ambang anugerah daripada surat makluman</h2><div class="row"><div class="col-md-6"><strong>Heavy Skills</strong><p class="mb-0">Emas 90-100, Perak 80-89, Gangsa 70-79, Medallion 65-69.</p></div><div class="col-md-6"><strong>Light Skills</strong><p class="mb-0">Emas 95-100, Perak 90-94, Gangsa 85-89, Medallion 75-84.</p></div></div></div></div></section>
<?php require BASE_PATH.'/partials/footer.php'; ?>
