<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';Auth::requireLogin(['technical','admin']);
if(is_post()){
    Csrf::verify();$registrationId=(int)input('registration_id');$score=(float)input('score');$category=(string)input('skill_category');$rank=(int)input('rank_position');$published=input('is_published')==='1'?1:0;$notes=trim((string)input('notes'));$errors=[];
    if($score<0||$score>100)$errors[]='Markah mesti antara 0 dan 100.';if(!in_array($category,['heavy','light'],true))$errors[]='Kategori kemahiran diperlukan.';$stmt=db()->prepare("SELECT id,competition_id,skill_id FROM registrations WHERE id=? AND status='approved'");$stmt->execute([$registrationId]);$registration=$stmt->fetch();if(!$registration)$errors[]='Pendaftaran belum diluluskan.';
    if($registration && $rank>0){$dup=db()->prepare("SELECT COUNT(*) FROM results res JOIN registrations r ON r.id=res.registration_id WHERE r.competition_id=? AND r.skill_id=? AND res.rank_position=? AND res.registration_id<>?");$dup->execute([(int)$registration['competition_id'],(int)$registration['skill_id'],$rank,$registrationId]);if((int)$dup->fetchColumn()>0)$errors[]='Kedudukan tersebut telah digunakan oleh peserta lain dalam bidang yang sama.';}
    if(!$errors){$award=CompetitionService::medalForScore($score,$category)??'Tiada';$stmt=db()->prepare("INSERT INTO results(registration_id,score,skill_category,award,rank_position,is_published,notes,entered_by,published_at) VALUES(?,?,?,?,?,?,?,?,IF(?=1,NOW(),NULL)) ON DUPLICATE KEY UPDATE score=VALUES(score),skill_category=VALUES(skill_category),award=VALUES(award),rank_position=VALUES(rank_position),is_published=VALUES(is_published),notes=VALUES(notes),entered_by=VALUES(entered_by),published_at=IF(VALUES(is_published)=1,COALESCE(published_at,NOW()),NULL)");$stmt->execute([$registrationId,$score,$category,$award,$rank?:null,$published,$notes?:null,Auth::id(),$published]);audit(Auth::id(),'save','result',$registrationId,['score'=>$score,'award'=>$award,'published'=>$published]);flash('success','Keputusan disimpan.');redirect('pegawai_teknikal/keputusan.php');}
    flash('error',implode(' ',$errors));redirect('pegawai_teknikal/keputusan.php');
}
$skillId=(int)($_GET['skill_id']??0);$skills=all_skills();$sql="SELECT r.id registration_id,r.participant_name,r.institution,s.name skill_name,z.name zone_name,res.score,res.skill_category,res.award,res.rank_position,res.is_published,res.notes FROM registrations r JOIN skills s ON s.id=r.skill_id JOIN zones z ON z.id=r.zone_id LEFT JOIN results res ON res.registration_id=r.id WHERE r.status='approved'";$params=[];if($skillId){$sql.=' AND r.skill_id=?';$params[]=$skillId;}$sql.=' ORDER BY s.sort_order,z.sort_order';$stmt=db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$pageTitle='Pengurusan Keputusan';$activePage='technical';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';require BASE_PATH.'/partials/flash.php';?>
<section class="dashboard-header"><div class="container text-center"><h1>Pengurusan Keputusan</h1><p>Anugerah dikira secara automatik berdasarkan kategori Heavy atau Light Skills.</p></div></section><section class="container py-4"><form method="get" class="card card-body mb-4"><div class="row g-3"><div class="col-md-10"><select name="skill_id" class="form-select"><option value="0">Semua bidang</option><?php foreach($skills as $s):?><option value="<?= (int)$s['id'] ?>" <?= selected($skillId,$s['id']) ?>><?= e($s['name']) ?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Tapis</button></div></div></form><div class="row g-3"><?php foreach($rows as $r):?><div class="col-xl-6"><form method="post" class="card shadow-sm h-100"><div class="card-body"><?= Csrf::field() ?><input type="hidden" name="registration_id" value="<?= (int)$r['registration_id'] ?>"><div class="d-flex justify-content-between"><div><h2 class="h5 mb-1"><?= e($r['participant_name']) ?></h2><p class="text-muted mb-3"><?= e($r['skill_name']) ?> · <?= e($r['zone_name']) ?></p></div><?php if($r['award']):?><span class="badge <?= e(CompetitionService::medalBadge($r['award'])) ?> align-self-start"><?= e($r['award']) ?></span><?php endif;?></div><div class="row g-2"><div class="col-4"><label class="form-label">Markah</label><input type="number" min="0" max="100" step="0.01" name="score" class="form-control" value="<?= e($r['score']??'') ?>" required></div><div class="col-4"><label class="form-label">Kategori</label><select name="skill_category" class="form-select" required><option value="">Pilih</option><option value="heavy" <?= selected($r['skill_category']??'','heavy') ?>>Heavy</option><option value="light" <?= selected($r['skill_category']??'','light') ?>>Light</option></select></div><div class="col-4"><label class="form-label">Kedudukan</label><input type="number" min="1" name="rank_position" class="form-control" value="<?= e($r['rank_position']??'') ?>"></div><div class="col-12"><label class="form-label">Catatan</label><input name="notes" class="form-control" value="<?= e($r['notes']??'') ?>"></div><div class="col-12 form-check ms-2"><input type="checkbox" class="form-check-input" id="pub<?= (int)$r['registration_id'] ?>" name="is_published" value="1" <?= checked((bool)($r['is_published']??false)) ?>><label class="form-check-label" for="pub<?= (int)$r['registration_id'] ?>">Terbitkan kepada umum</label></div></div><button class="btn btn-primary mt-3">Simpan Keputusan</button></div></form></div><?php endforeach;?><?php if(!$rows):?><div class="col-12"><div class="alert alert-info">Tiada peserta diluluskan.</div></div><?php endif;?></div></section><?php require BASE_PATH.'/partials/footer.php';?>
