<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';Auth::requireLogin(['technical','admin']);$me=Auth::user();
if(is_post()){
    Csrf::verify();$id=(int)input('id');$status=(string)input('status');
    if(!in_array($status,['active','disabled'],true)){flash('error','Status tidak sah.');redirect('pegawai_teknikal/pengguna.php');}
    $stmt=db()->prepare('SELECT id,role,status FROM users WHERE id=?');$stmt->execute([$id]);$target=$stmt->fetch();
    if(!$target||$id===Auth::id()){flash('error','Pengguna tidak sah.');redirect('pegawai_teknikal/pengguna.php');}
    if($me['role']!=='admin' && $target['role']!=='coach'){http_response_code(403);exit('Hanya admin boleh mengurus akaun pegawai teknikal.');}
    $stmt=db()->prepare('UPDATE users SET status=?,approved_at=IF(?=\'active\',NOW(),approved_at),approved_by=? WHERE id=?');$stmt->execute([$status,$status,Auth::id(),$id]);audit(Auth::id(),'change_status','user',$id,['status'=>$status]);flash('success','Status pengguna dikemas kini.');redirect('pegawai_teknikal/pengguna.php');
}
$role=(string)($_GET['role']??'');$status=(string)($_GET['status']??'');$sql='SELECT u.*,z.name zone_name FROM users u LEFT JOIN zones z ON z.id=u.zone_id WHERE u.id<>?';$params=[Auth::id()];if(in_array($role,['coach','technical','admin'],true)){$sql.=' AND u.role=?';$params[]=$role;}if(in_array($status,['pending','active','disabled'],true)){$sql.=' AND u.status=?';$params[]=$status;}$sql.=' ORDER BY FIELD(u.status,\'pending\',\'active\',\'disabled\'),u.created_at DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$users=$stmt->fetchAll();
$pageTitle='Pengurusan Pengguna';$activePage='technical';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';require BASE_PATH.'/partials/flash.php';?>
<section class="dashboard-header"><div class="container text-center"><h1>Pengurusan Pengguna</h1><p>Kelulusan jurulatih dan kawalan akses pegawai.</p></div></section><section class="container py-4"><form class="card card-body mb-4" method="get"><div class="row g-3"><div class="col-md-5"><select name="role" class="form-select"><option value="">Semua peranan</option><option value="coach" <?= selected($role,'coach') ?>>Jurulatih</option><option value="technical" <?= selected($role,'technical') ?>>Pegawai Teknikal</option><option value="admin" <?= selected($role,'admin') ?>>Admin</option></select></div><div class="col-md-5"><select name="status" class="form-select"><option value="">Semua status</option><option value="pending" <?= selected($status,'pending') ?>>Menunggu</option><option value="active" <?= selected($status,'active') ?>>Aktif</option><option value="disabled" <?= selected($status,'disabled') ?>>Dinyahaktif</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Tapis</button></div></div></form><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Nama</th><th>Peranan</th><th>Kolej/Zon</th><th>Status</th><th>Tindakan</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?= e($u['full_name']) ?><br><small><?= e($u['email']) ?></small></td><td><?= e(ucfirst($u['role'])) ?></td><td><?= e($u['institution']??'-') ?><br><small><?= e($u['zone_name']??'-') ?></small></td><td><span class="status status-<?= e($u['status']) ?>"><?= e(ucfirst($u['status'])) ?></span></td><td><?php if($me['role']==='admin'||$u['role']==='coach'):?><div class="d-flex gap-2"><form method="post"><?= Csrf::field() ?><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><input type="hidden" name="status" value="active"><button class="btn btn-sm btn-success">Aktifkan</button></form><form method="post"><?= Csrf::field() ?><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><input type="hidden" name="status" value="disabled"><button class="btn btn-sm btn-outline-danger">Nyahaktif</button></form></div><?php else:?><span class="text-muted">Admin sahaja</span><?php endif;?></td></tr><?php endforeach;?><?php if(!$users):?><tr><td colspan="5" class="text-center text-muted">Tiada pengguna.</td></tr><?php endif;?></tbody></table></div></section><?php require BASE_PATH.'/partials/footer.php';?>
