<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';
Auth::requireLogin(['technical','admin']);

if(is_post()){
    Csrf::verify();
    $action=(string)input('action','create');
    if($action==='status'){
        $id=(int)input('id');$status=(string)input('status');
        if(!in_array($status,['draft','registration','ongoing','completed','archived'],true)){flash('error','Status tidak sah.');redirect('pegawai_teknikal/pertandingan.php');}
        db()->beginTransaction();
        if($status==='registration')db()->prepare("UPDATE competitions SET status='completed' WHERE status='registration' AND id<>?")->execute([$id]);
        db()->prepare('UPDATE competitions SET status=? WHERE id=?')->execute([$status,$id]);
        db()->commit();audit(Auth::id(),'change_status','competition',$id,['status'=>$status]);flash('success','Status pertandingan dikemas kini.');redirect('pegawai_teknikal/pertandingan.php');
    }
    $code=strtoupper(trim((string)input('code')));$name=trim((string)input('name'));$start=(string)input('start_date');$end=(string)input('end_date');$host=trim((string)input('host_zone'));$status=(string)input('status','draft');$errors=[];
    if($code===''||$name==='')$errors[]='Kod dan nama pertandingan diperlukan.';if(!$start||!$end||$end<$start)$errors[]='Julat tarikh tidak sah.';if(!in_array($status,['draft','registration'],true))$errors[]='Status awal tidak sah.';
    if(!$errors){try{db()->beginTransaction();if($status==='registration')db()->exec("UPDATE competitions SET status='completed' WHERE status='registration'");$stmt=db()->prepare('INSERT INTO competitions(code,name,level,start_date,end_date,host_zone,status,description) VALUES(?,?,\'national\',?,?,?,?,?)');$stmt->execute([$code,$name,$start,$end,$host?:null,$status,'Edisi pertandingan kebangsaan.']);$id=(int)db()->lastInsertId();$sourceId=(int)db()->query("SELECT id FROM competitions WHERE id<>$id ORDER BY start_date DESC LIMIT 1")->fetchColumn();if($sourceId){$stmt=db()->prepare('INSERT INTO competition_skills(competition_id,skill_id,venue_id,skill_category) SELECT ?,skill_id,venue_id,skill_category FROM competition_skills WHERE competition_id=?');$stmt->execute([$id,$sourceId]);}db()->commit();audit(Auth::id(),'create','competition',$id);flash('success','Edisi pertandingan dicipta dan pemetaan bidang/lokasi disalin.');redirect('pegawai_teknikal/pertandingan.php');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$errors[]='Gagal mencipta pertandingan. Pastikan kod adalah unik.';}}
    if($errors){flash('error',implode(' ',$errors));redirect('pegawai_teknikal/pertandingan.php');}
}
$rows=db()->query('SELECT c.*,COUNT(cs.id) skill_count FROM competitions c LEFT JOIN competition_skills cs ON cs.competition_id=c.id GROUP BY c.id ORDER BY c.start_date DESC')->fetchAll();
$pageTitle='Edisi Pertandingan';$activePage='technical';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';require BASE_PATH.'/partials/flash.php';
?>
<section class="dashboard-header"><div class="container text-center"><h1>Edisi Pertandingan</h1><p>Cipta edisi baharu dan buka atau tutup pendaftaran secara terkawal.</p></div></section>
<section class="container py-4"><div class="card card-body shadow-sm mb-4"><h2 class="h5">Cipta Edisi Baharu</h2><form method="post"><?= Csrf::field() ?><input type="hidden" name="action" value="create"><div class="row g-3"><div class="col-md-3"><label class="form-label">Kod</label><input name="code" class="form-control" placeholder="KVSKILLS-2026" required></div><div class="col-md-9"><label class="form-label">Nama</label><input name="name" class="form-control" required></div><div class="col-md-3"><label class="form-label">Tarikh Mula</label><input type="date" name="start_date" class="form-control" required></div><div class="col-md-3"><label class="form-label">Tarikh Tamat</label><input type="date" name="end_date" class="form-control" required></div><div class="col-md-3"><label class="form-label">Zon Hos</label><input name="host_zone" class="form-control"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="draft">Draf</option><option value="registration">Buka pendaftaran</option></select></div></div><button class="btn btn-primary mt-3">Cipta Edisi</button></form></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Edisi</th><th>Tarikh</th><th>Bidang</th><th>Status</th><th>Kemas kini</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?= e($r['code']) ?></strong><br><small><?= e($r['name']) ?></small></td><td><?= e(format_date($r['start_date'])) ?> - <?= e(format_date($r['end_date'])) ?></td><td><?= (int)$r['skill_count'] ?></td><td><span class="status status-<?= e($r['status']) ?>"><?= e($r['status']) ?></span></td><td><form method="post" class="d-flex gap-2"><?= Csrf::field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><select name="status" class="form-select form-select-sm"><option value="draft" <?= selected($r['status'],'draft') ?>>Draf</option><option value="registration" <?= selected($r['status'],'registration') ?>>Pendaftaran</option><option value="ongoing" <?= selected($r['status'],'ongoing') ?>>Berlangsung</option><option value="completed" <?= selected($r['status'],'completed') ?>>Selesai</option><option value="archived" <?= selected($r['status'],'archived') ?>>Arkib</option></select><button class="btn btn-sm btn-primary">Simpan</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require BASE_PATH.'/partials/footer.php'; ?>
