<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';
if(is_post()){
    Csrf::verify();$errors=[];
    $code=(string)input('registration_code');$expected=(string)env('TECHNICAL_REGISTRATION_CODE','');
    $name=trim((string)input('full_name'));$email=mb_strtolower(trim((string)input('email')));$phone=trim((string)input('phone'));$password=(string)input('password');$confirm=(string)input('password_confirmation');
    if($expected===''||!hash_equals($expected,$code))$errors[]='Kod pendaftaran pegawai tidak sah.';
    if(mb_strlen($name)<3)$errors[]='Nama penuh diperlukan.';if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='E-mel tidak sah.';if(strlen($password)<12)$errors[]='Kata laluan minimum 12 aksara.';if($password!==$confirm)$errors[]='Pengesahan kata laluan tidak sepadan.';
    if(!$errors){try{$stmt=db()->prepare("INSERT INTO users(role,status,full_name,email,phone,password_hash) VALUES('technical','pending',?,?,?,?)");$stmt->execute([$name,$email,$phone?:null,password_hash($password,PASSWORD_DEFAULT)]);flash('success','Akaun pegawai teknikal didaftarkan dan menunggu kelulusan admin.');redirect('pegawai_teknikal/login.php');}catch(PDOException $e){$errors[]=$e->getCode()==='23000'?'E-mel telah digunakan.':'Pendaftaran gagal.';}}
    if($errors)fail_validation($errors,'pegawai_teknikal/register.php');
}
$pageTitle='Daftar Pegawai Teknikal';require BASE_PATH.'/partials/head.php';$errors=validation_errors();?>
<div class="login-wrapper"><a href="<?= e(url('pegawai_teknikal/login.php')) ?>" class="login-back"><i class="fa-solid fa-arrow-left"></i>Kembali</a><div class="login-card wide-form"><h2>Daftar Pegawai Teknikal</h2><div class="login-underline"></div><p class="text-muted">Pendaftaran memerlukan kod autorisasi dan kelulusan pentadbir.</p><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $er):?><li><?= e($er) ?></li><?php endforeach;?></ul></div><?php endif;?><form method="post"><?= Csrf::field() ?><div class="row g-3"><div class="col-12"><label class="form-label">Kod Pendaftaran</label><input type="password" class="form-control" name="registration_code" required></div><div class="col-12"><label class="form-label">Nama Penuh</label><input class="form-control" name="full_name" value="<?= e(old('full_name')) ?>" required></div><div class="col-md-6"><label class="form-label">E-mel</label><input type="email" class="form-control" name="email" value="<?= e(old('email')) ?>" required></div><div class="col-md-6"><label class="form-label">Telefon</label><input class="form-control" name="phone" value="<?= e(old('phone')) ?>"></div><div class="col-md-6"><label class="form-label">Kata Laluan</label><input type="password" class="form-control" name="password" minlength="12" required></div><div class="col-md-6"><label class="form-label">Ulang Kata Laluan</label><input type="password" class="form-control" name="password_confirmation" minlength="12" required></div></div><button class="login-btn mt-4">Daftar</button></form></div></div></body></html>
