<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';
Auth::requireLogin('coach'); Auth::refresh(); $user=Auth::user();
$stmt=db()->prepare("SELECT COUNT(*) total,SUM(status='approved') approved,SUM(status='submitted') submitted,SUM(status='rejected') rejected FROM registrations WHERE coach_user_id=?");$stmt->execute([Auth::id()]);$counts=$stmt->fetch();
$stmt=db()->prepare("SELECT r.*,s.name AS skill_name,z.name AS zone_name FROM registrations r JOIN skills s ON s.id=r.skill_id JOIN zones z ON z.id=r.zone_id WHERE r.coach_user_id=? ORDER BY r.created_at DESC LIMIT 8");$stmt->execute([Auth::id()]);$recent=$stmt->fetchAll();
$pageTitle='Dashboard Jurulatih';$activePage='coach';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';require BASE_PATH.'/partials/flash.php';?>
<section class="dashboard-header"><div class="container text-center"><h1>Dashboard Jurulatih</h1><p>Selamat datang, <?= e($user['full_name']) ?> · <?= e($user['zone_name']??'Zon belum ditetapkan') ?></p></div></section>
<section class="container py-4"><div class="row g-3 mb-4"><?php foreach([['total','Jumlah','fa-clipboard-list'],['submitted','Menunggu','fa-clock'],['approved','Diluluskan','fa-circle-check'],['rejected','Ditolak','fa-circle-xmark']] as [$k,$label,$icon]):?><div class="col-6 col-lg-3"><div class="stat-card"><i class="fa-solid <?= e($icon) ?>"></i><strong><?= (int)($counts[$k]??0) ?></strong><span><?= e($label) ?></span></div></div><?php endforeach;?></div>
<div class="row g-4"><div class="col-lg-4"><div class="card shadow-sm h-100"><div class="card-body"><h2 class="h5">Profil Jurulatih</h2><dl class="profile-list"><dt>Nama</dt><dd><?= e($user['full_name']) ?></dd><dt>Kolej</dt><dd><?= e($user['institution']??'-') ?></dd><dt>Zon</dt><dd><?= e($user['zone_name']??'-') ?></dd><dt>E-mel</dt><dd><?= e($user['email']) ?></dd></dl><a href="<?= e(url('jurulatih/pendaftaran.php')) ?>" class="btn btn-primary w-100"><i class="fa-solid fa-user-plus"></i> Daftar Peserta</a></div></div></div>
<div class="col-lg-8"><div class="card shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Pendaftaran Terkini</h2><a href="<?= e(url('jurulatih/pendaftaran.php')) ?>">Lihat semua</a></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Peserta</th><th>Bidang</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?= e($r['participant_name']) ?></td><td><?= e($r['skill_name']) ?></td><td><span class="status status-<?= e($r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="3" class="text-center text-muted">Belum ada pendaftaran.</td></tr><?php endif;?></tbody></table></div></div></div></div></div></section>
<?php require BASE_PATH.'/partials/footer.php';?>
