<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';
Auth::requireLogin('coach');Auth::refresh();$user=Auth::user();$competition=registration_competition();$skills=all_skills();
if(is_post()){
    Csrf::verify();$action=(string)input('action','create');
    if($action==='delete'){
        $id=(int)input('id');$stmt=db()->prepare("DELETE FROM registrations WHERE id=? AND coach_user_id=? AND status IN ('submitted','rejected','draft')");$stmt->execute([$id,Auth::id()]);flash('success',$stmt->rowCount()?'Pendaftaran dipadam.':'Pendaftaran tidak boleh dipadam.');redirect('jurulatih/pendaftaran.php');
    }
    if(!$competition){flash('error','Tiada pertandingan yang sedang membuka pendaftaran.');redirect('jurulatih/pendaftaran.php');}
    $skillId=(int)input('skill_id');$skill=skill_by_id($skillId);$participant=trim((string)input('participant_name'));$email=trim((string)input('participant_email'));$phone=trim((string)input('participant_phone'));$institution=trim((string)input('institution',$user['institution']??''));$assistant=trim((string)input('assistant_name'));$model=trim((string)input('model_name'));$errors=[];
    if(!$skill)$errors[]='Bidang tidak sah.';if(mb_strlen($participant)<3)$errors[]='Nama peserta diperlukan.';if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='E-mel peserta tidak sah.';if($institution==='')$errors[]='Nama kolej diperlukan.';if(empty($user['zone_id']))$errors[]='Akaun jurulatih belum mempunyai zon.';
    if($skill)$errors=array_merge($errors,CompetitionService::validateHelpers($skill,['assistant'=>$assistant!==''?[$assistant]:[],'model'=>$model!==''?[$model]:[]]));
    if(!$errors){
        try{db()->beginTransaction();$stmt=db()->prepare("INSERT INTO registrations(competition_id,zone_id,skill_id,coach_user_id,participant_name,participant_email,participant_phone,institution,status,submitted_at) VALUES(?,?,?,?,?,?,?,?,'submitted',NOW())");$stmt->execute([(int)$competition['id'],(int)$user['zone_id'],$skillId,Auth::id(),$participant,$email?:null,$phone?:null,$institution]);$regId=(int)db()->lastInsertId();$hs=db()->prepare('INSERT INTO registration_helpers(registration_id,helper_type,full_name) VALUES(?,?,?)');if($assistant!=='')$hs->execute([$regId,'assistant',$assistant]);if($model!=='')$hs->execute([$regId,'model',$model]);db()->commit();audit(Auth::id(),'create','registration',$regId,['skill_id'=>$skillId]);clear_old();flash('success','Pendaftaran peserta dihantar untuk pengesahan.');redirect('jurulatih/pendaftaran.php');}
        catch(PDOException $e){if(db()->inTransaction())db()->rollBack();$errors[]=$e->getCode()==='23000'?'Zon anda telah mempunyai pendaftaran untuk bidang ini.':'Pendaftaran gagal disimpan.';}
        catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$errors[]='Pendaftaran gagal disimpan.';}
    }
    if($errors)fail_validation($errors,'jurulatih/pendaftaran.php');
}
$stmt=db()->prepare("SELECT r.*,s.name skill_name,s.assistant_note,GROUP_CONCAT(CONCAT(h.helper_type,': ',h.full_name) SEPARATOR '||') helpers FROM registrations r JOIN skills s ON s.id=r.skill_id LEFT JOIN registration_helpers h ON h.registration_id=r.id WHERE r.coach_user_id=? GROUP BY r.id ORDER BY s.sort_order");$stmt->execute([Auth::id()]);$rows=$stmt->fetchAll();
$pageTitle='Pendaftaran Peserta';$activePage='coach';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';require BASE_PATH.'/partials/flash.php';?>
<section class="dashboard-header"><div class="container text-center"><h1>Pendaftaran Peserta</h1><p>Satu penyertaan bagi setiap zon dan bidang. Peraturan pembantu disemak oleh backend.</p></div></section>
<section class="container py-4"><?php if(!$competition):?><div class="alert alert-warning">Tiada pertandingan yang sedang membuka pendaftaran. Pegawai teknikal perlu membuka edisi pertandingan terlebih dahulu.</div><?php endif;?><div class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3">Daftar Peserta Baharu</h2><form method="post" id="registrationForm"><fieldset <?= !$competition?'disabled':'' ?>><?= Csrf::field() ?><input type="hidden" name="action" value="create"><div class="row g-3"><div class="col-md-6"><label class="form-label">Bidang</label><select name="skill_id" id="skillSelect" class="form-select" required><option value="">Pilih bidang</option><?php foreach($skills as $s):?><option value="<?= (int)$s['id'] ?>" data-assistant="<?= (int)$s['assistant_count'] ?>" data-model="<?= (int)$s['model_count'] ?>" data-note="<?= e($s['assistant_note']) ?>" <?= selected(old('skill_id'),$s['id']) ?>><?= e($s['name']) ?></option><?php endforeach;?></select><div id="helperNote" class="form-text"></div></div><div class="col-md-6"><label class="form-label">Nama Peserta</label><input name="participant_name" class="form-control" value="<?= e(old('participant_name')) ?>" required></div><div class="col-md-6"><label class="form-label">E-mel Peserta (opsyenal)</label><input type="email" name="participant_email" class="form-control" value="<?= e(old('participant_email')) ?>"></div><div class="col-md-6"><label class="form-label">Telefon Peserta (opsyenal)</label><input name="participant_phone" class="form-control" value="<?= e(old('participant_phone')) ?>"></div><div class="col-md-6"><label class="form-label">Kolej Vokasional</label><input name="institution" class="form-control" value="<?= e(old('institution',$user['institution']??'')) ?>" required></div><div class="col-md-3 helper-field" id="assistantField"><label class="form-label">Nama Pembantu</label><input name="assistant_name" class="form-control" value="<?= e(old('assistant_name')) ?>"></div><div class="col-md-3 helper-field" id="modelField"><label class="form-label">Nama Model</label><input name="model_name" class="form-control" value="<?= e(old('model_name')) ?>"></div></div><button class="btn btn-primary mt-4"><i class="fa-solid fa-paper-plane"></i> Hantar Pendaftaran</button></fieldset></form></div></div>
<div class="card shadow-sm"><div class="card-body"><h2 class="h5">Pendaftaran Saya</h2><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Peserta</th><th>Bidang</th><th>Pembantu/Model</th><th>Status</th><th>Tindakan</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?= e($r['participant_name']) ?><br><small><?= e($r['institution']) ?></small></td><td><?= e($r['skill_name']) ?></td><td><?php foreach(array_filter(explode('||',(string)$r['helpers'])) as $h):?><div><?= e($h) ?></div><?php endforeach;?><?= !$r['helpers']?'<span class="text-muted">Tiada</span>':'' ?></td><td><span class="status status-<?= e($r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span><?php if($r['rejection_reason']):?><div class="small text-danger mt-1"><?= e($r['rejection_reason']) ?></div><?php endif;?></td><td><?php if(in_array($r['status'],['submitted','rejected','draft'],true)):?><form method="post" onsubmit="return confirm('Padam pendaftaran ini?')"><?= Csrf::field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger">Padam</button></form><?php else:?><span class="text-muted">-</span><?php endif;?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="text-center text-muted">Belum ada pendaftaran.</td></tr><?php endif;?></tbody></table></div></div></div></section>
<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('skillSelect'),a=document.getElementById('assistantField'),m=document.getElementById('modelField'),n=document.getElementById('helperNote');function update(){const o=s.options[s.selectedIndex];const ac=Number(o?.dataset.assistant||0),mc=Number(o?.dataset.model||0);a.style.display=ac?'block':'none';m.style.display=mc?'block':'none';a.querySelector('input').required=ac>0;m.querySelector('input').required=mc>0;n.textContent=o?.dataset.note||'';}s.addEventListener('change',update);update();});</script>
<?php require BASE_PATH.'/partials/footer.php';?>
